version: '2'

services:
  rabbitmq:
    image: bitnami/rabbitmq:3.8
    ports:
      - '4370:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=root
      - RABBITMQ_PASSWORD=root
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq
      - RABBITMQ_HOST=rabbitmq
      # - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
    volumes:
      - 'rabbitmqstats_data:/bitnami'
    networks: 
      - backend

volumes:
  rabbitmqstats_data:
    driver: local

networks: 
  backend:
    driver: bridge
